
import java.sql.*;
import javax.swing.JOptionPane;
import project.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zhengkai Xie
 */
public class resetPassword extends javax.swing.JFrame {

    /**
     * Creates new form resetPassword
     */
    public resetPassword() {
        initComponents();
    }
    String code;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleText = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        subtitleText = new javax.swing.JLabel();
        emailText = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        verificationCodeText = new javax.swing.JLabel();
        verificationCodeInput = new javax.swing.JPasswordField();
        sendEmailButton = new javax.swing.JButton();
        newPasswordText = new javax.swing.JLabel();
        newPasswordInput = new javax.swing.JPasswordField();
        repeatNewPasswordText = new javax.swing.JLabel();
        repeatNewPasswordInput = new javax.swing.JPasswordField();
        resetPasswordButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();
        resetBySecurityQuestionLink = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleText.setFont(new java.awt.Font("Bernard MT Condensed", 1, 36)); // NOI18N
        titleText.setText("ZX Library System");
        titleText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleTextMouseClicked(evt);
            }
        });
        getContentPane().add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-button.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        subtitleText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        subtitleText.setForeground(new java.awt.Color(255, 255, 255));
        subtitleText.setText("Reset password");
        getContentPane().add(subtitleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        emailText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailText.setForeground(new java.awt.Color(255, 255, 255));
        emailText.setText("Email");
        getContentPane().add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        emailInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 365, -1));

        verificationCodeText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        verificationCodeText.setForeground(new java.awt.Color(255, 255, 255));
        verificationCodeText.setText("Verification Code");
        getContentPane().add(verificationCodeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        verificationCodeInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(verificationCodeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 365, -1));

        sendEmailButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sendEmailButton.setText("Send Email");
        sendEmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendEmailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, -1, -1));

        newPasswordText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newPasswordText.setForeground(new java.awt.Color(255, 255, 255));
        newPasswordText.setText("New Password");
        getContentPane().add(newPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        newPasswordInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(newPasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 365, -1));

        repeatNewPasswordText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        repeatNewPasswordText.setForeground(new java.awt.Color(255, 255, 255));
        repeatNewPasswordText.setText("Repeat New Password");
        getContentPane().add(repeatNewPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        repeatNewPasswordInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(repeatNewPasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 365, -1));

        resetPasswordButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetPasswordButton.setText("Reset Password");
        resetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetPasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        loginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginButton.setText("Log in");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        signupButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signupButton.setText("Sign up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, -1, -1));

        resetBySecurityQuestionLink.setForeground(new java.awt.Color(255, 255, 255));
        resetBySecurityQuestionLink.setText("Cannot get the code?");
        resetBySecurityQuestionLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetBySecurityQuestionLinkMouseClicked(evt);
            }
        });
        getContentPane().add(resetBySecurityQuestionLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 325, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        int a=JOptionPane.showConfirmDialog(null, "Do you want to exit the application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        setVisible(false);
        new Signup().setVisible(true);
    }//GEN-LAST:event_signupButtonActionPerformed

    private void sendEmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailButtonActionPerformed
        StringBuilder emailSb = new StringBuilder(emailInput.getText());
        String email = UpdateData.dealSpcialSymbols(emailSb);
        code = new Signup().generateCode();
        String emailContent = "Your verification code is " + code + ".";
        Email.sendEmail(email, emailContent, "Email Verification", 1);
    }//GEN-LAST:event_sendEmailButtonActionPerformed

    private void titleTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleTextMouseClicked
        setVisible(false);
        new home(false, "").setVisible(true);
    }//GEN-LAST:event_titleTextMouseClicked

    private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
        StringBuilder emailSb = new StringBuilder(emailInput.getText());
        String email = UpdateData.dealSpcialSymbols(emailSb);
        StringBuilder verificationCodeSb = new StringBuilder(verificationCodeInput.getText());
        String verificationCode = UpdateData.dealSpcialSymbols(verificationCodeSb);
        StringBuilder newPasswordSb = new StringBuilder(newPasswordInput.getText());
        String newPassword = UpdateData.dealSpcialSymbols(newPasswordSb);
        StringBuilder newPasswordRepeatSb = new StringBuilder(repeatNewPasswordInput.getText());
        String newPasswordRepeat = UpdateData.dealSpcialSymbols(newPasswordRepeatSb);
        if(email.equals("") || newPassword.equals("") || newPasswordRepeat.equals("") || verificationCode.equals("")){
            JOptionPane.showMessageDialog(null, "All field is required.");
        }else if(code==null || !verificationCode.equals(code)){
            JOptionPane.showMessageDialog(null, "Email not sent or code entered is wrong.");
        }else if(!newPassword.equals(newPasswordRepeat)){
            JOptionPane.showMessageDialog(null, "Need to repeat the same password!");
        }else{
            ResultSet rs=Select.getData("select *from users where email='"+email+"'");
            try{
                if(rs.next()){
                    if(rs.getString(3).equals(newPassword)){
                        JOptionPane.showMessageDialog(null, "Entered the old password, need to enter a new one!");
                    }else{
                        UpdateData.setData("update users set password='"+newPassword+"' where email='"+email+"'", "Password set successfully!");
                        setVisible(false);
                        new Login().setVisible(true);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_resetPasswordButtonActionPerformed

    private void resetBySecurityQuestionLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBySecurityQuestionLinkMouseClicked
        setVisible(false);
        new resetPasswordBySecurityQuestion().setVisible(true);
    }//GEN-LAST:event_resetBySecurityQuestionLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField newPasswordInput;
    private javax.swing.JLabel newPasswordText;
    private javax.swing.JPasswordField repeatNewPasswordInput;
    private javax.swing.JLabel repeatNewPasswordText;
    private javax.swing.JLabel resetBySecurityQuestionLink;
    private javax.swing.JButton resetPasswordButton;
    private javax.swing.JButton sendEmailButton;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel subtitleText;
    private javax.swing.JLabel titleText;
    private javax.swing.JPasswordField verificationCodeInput;
    private javax.swing.JLabel verificationCodeText;
    // End of variables declaration//GEN-END:variables
}
