
import javax.swing.JOptionPane;
import java.sql.*;
import project.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zhengkai Xie
 */
public class resetPasswordBySecurityQuestion extends javax.swing.JFrame {

    /**
     * Creates new form resetPasswordBySecurityQuestion
     */
    String email;
    String securityQuestion;
    public resetPasswordBySecurityQuestion() {
        initComponents();
        securityQuestionData.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleText = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        subtitleText = new javax.swing.JLabel();
        newPasswordText = new javax.swing.JLabel();
        newPasswordInput = new javax.swing.JPasswordField();
        repeatNewPasswordText = new javax.swing.JLabel();
        repeatNewPasswordInput = new javax.swing.JPasswordField();
        resetPasswordButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        securityQuestionData = new javax.swing.JTextField();
        answerInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        checkButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleText.setFont(new java.awt.Font("Bernard MT Condensed", 1, 36)); // NOI18N
        titleText.setText("ZX Library System");
        titleText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleTextMouseClicked(evt);
            }
        });
        getContentPane().add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-button.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        subtitleText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        subtitleText.setForeground(new java.awt.Color(255, 255, 255));
        subtitleText.setText("Reset password");
        getContentPane().add(subtitleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        newPasswordText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newPasswordText.setForeground(new java.awt.Color(255, 255, 255));
        newPasswordText.setText("New Password");
        getContentPane().add(newPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 407, -1, -1));

        newPasswordInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(newPasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 404, 365, -1));

        repeatNewPasswordText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        repeatNewPasswordText.setForeground(new java.awt.Color(255, 255, 255));
        repeatNewPasswordText.setText("Repeat New Password");
        getContentPane().add(repeatNewPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 448, -1, -1));

        repeatNewPasswordInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(repeatNewPasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 445, 365, -1));

        resetPasswordButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetPasswordButton.setText("Reset Password");
        resetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetPasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));

        loginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginButton.setText("Log in");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, -1, -1));

        signupButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signupButton.setText("Sign up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Answer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 366, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Security Question");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 325, -1, -1));

        securityQuestionData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(securityQuestionData, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 322, 365, -1));

        answerInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(answerInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 363, 365, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 284, -1, -1));

        emailInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 284, 365, -1));

        checkButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 284, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleTextMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new home(false, "").setVisible(true);
    }//GEN-LAST:event_titleTextMouseClicked

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do you want to exit the application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
        StringBuilder answerSb = new StringBuilder(answerInput.getText());
        String answer = UpdateData.dealSpcialSymbols(answerSb);
        StringBuilder newPasswordSb = new StringBuilder(newPasswordInput.getText());
        String newPassword = UpdateData.dealSpcialSymbols(newPasswordSb);
        StringBuilder newPasswordRepeatSb = new StringBuilder(repeatNewPasswordInput.getText());
        String newPasswordRepeat = UpdateData.dealSpcialSymbols(newPasswordRepeatSb);
        if(email.equals("") || answer.equals("") || newPassword.equals("") || newPasswordRepeat.equals("")){
            JOptionPane.showMessageDialog(null, "All field is required.");
        }else if(!newPassword.equals(newPasswordRepeat)){
            JOptionPane.showMessageDialog(null, "Need to repeat the same password!");
        }else{
            ResultSet rs=Select.getData("select *from users where email='"+email+"' and answer='"+answer+"'");
            try{
                if(rs.next()){
                    if(rs.getString(3).equals(newPassword)){
                        JOptionPane.showMessageDialog(null, "Entered the old password, need to enter a new one!");
                    }else{
                        UpdateData.setData("update users set password='"+newPassword+"' where email='"+email+"'", "Password set successfully!");
                        setVisible(false);
                        new Login().setVisible(true);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Answer to the security question is wrong!");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_resetPasswordButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        setVisible(false);
        new Signup().setVisible(true);
    }//GEN-LAST:event_signupButtonActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        StringBuilder emailSb = new StringBuilder(emailInput.getText());
        email = UpdateData.dealSpcialSymbols(emailSb);
        ResultSet rs = Select.getData("select *from users where email='"+email+"'");
        try{
            if(Email.verifyEmailFormat(email) && rs.next()){
                securityQuestion = rs.getString(4);
                securityQuestionData.setText(securityQuestion);
            }else{
                JOptionPane.showMessageDialog(null, "Email is invalid or not registered!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_checkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetPasswordBySecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetPasswordBySecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetPasswordBySecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetPasswordBySecurityQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetPasswordBySecurityQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerInput;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField newPasswordInput;
    private javax.swing.JLabel newPasswordText;
    private javax.swing.JPasswordField repeatNewPasswordInput;
    private javax.swing.JLabel repeatNewPasswordText;
    private javax.swing.JButton resetPasswordButton;
    private javax.swing.JTextField securityQuestionData;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel subtitleText;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
