
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
import project.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zhengkai Xie
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Sign up
     */
    public Signup() {
        initComponents();
    }
    String code;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleText = new javax.swing.JLabel();
        subtitleText = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        nameText = new javax.swing.JLabel();
        passwordText = new javax.swing.JLabel();
        emailText = new javax.swing.JLabel();
        emailVerificationText = new javax.swing.JLabel();
        securityQuestionText = new javax.swing.JLabel();
        answerText = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        emailVerificationInput = new javax.swing.JPasswordField();
        securityQuestionInput = new javax.swing.JComboBox<>();
        answerInput = new javax.swing.JTextField();
        emailVerifyButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        repeatPasswordInput = new javax.swing.JPasswordField();
        passwordInput = new javax.swing.JPasswordField();
        repeatPasswordText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleText.setFont(new java.awt.Font("Bernard MT Condensed", 1, 36)); // NOI18N
        titleText.setText("ZX Library System");
        titleText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleTextMouseClicked(evt);
            }
        });
        getContentPane().add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        subtitleText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        subtitleText.setForeground(new java.awt.Color(255, 255, 255));
        subtitleText.setText("Sign up");
        getContentPane().add(subtitleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-button.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1247, 0, 30, 30));

        nameText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        nameText.setText("User Name");
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        passwordText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordText.setForeground(new java.awt.Color(255, 255, 255));
        passwordText.setText("Password");
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        emailText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailText.setForeground(new java.awt.Color(255, 255, 255));
        emailText.setText("Email");
        getContentPane().add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        emailVerificationText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailVerificationText.setForeground(new java.awt.Color(255, 255, 255));
        emailVerificationText.setText("Email Verification Code");
        getContentPane().add(emailVerificationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        securityQuestionText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        securityQuestionText.setForeground(new java.awt.Color(255, 255, 255));
        securityQuestionText.setText("Security Question");
        getContentPane().add(securityQuestionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        answerText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        answerText.setForeground(new java.awt.Color(255, 255, 255));
        answerText.setText("Answer");
        getContentPane().add(answerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        nameInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 416, -1));

        emailInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 416, -1));

        emailVerificationInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(emailVerificationInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 416, -1));

        securityQuestionInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        securityQuestionInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is the name of your favorite teacher in childhood?", "What is your favorite sports team?", "What is the city where you were born?", "What is your favorite food for lunch?" }));
        getContentPane().add(securityQuestionInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, -1));

        answerInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(answerInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 416, -1));

        emailVerifyButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailVerifyButton.setText("Send Code");
        emailVerifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailVerifyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(emailVerifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, -1, -1));

        signupButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signupButton.setText("Sign up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, -1, -1));

        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginButton.setText("Log in");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 570, -1, -1));

        repeatPasswordInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(repeatPasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 416, -1));

        passwordInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 416, -1));

        repeatPasswordText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        repeatPasswordText.setForeground(new java.awt.Color(255, 255, 255));
        repeatPasswordText.setText("Repeat Password");
        getContentPane().add(repeatPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        int a=JOptionPane.showConfirmDialog(null, "Do you want to exit the application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void emailVerifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailVerifyButtonActionPerformed
        String email = emailInput.getText();
        code=generateCode();
        String emailContent = "Your verification code is " + code + ".";
        Email.sendEmail(email, emailContent, "Email Verification", 0);
        
    }//GEN-LAST:event_emailVerifyButtonActionPerformed

    private void titleTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleTextMouseClicked
        setVisible(false);
        new home(false, "").setVisible(true);
    }//GEN-LAST:event_titleTextMouseClicked

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        StringBuilder nameSb = new StringBuilder(nameInput.getText());
        String name = UpdateData.dealSpcialSymbols(nameSb);
        StringBuilder emailSb = new StringBuilder(emailInput.getText());
        String email = UpdateData.dealSpcialSymbols(emailSb);
        StringBuilder passwordSb = new StringBuilder(passwordInput.getText());
        String password = UpdateData.dealSpcialSymbols(passwordSb);
        StringBuilder repeatPasswordSb = new StringBuilder(repeatPasswordInput.getText());
        String repeatPassword = UpdateData.dealSpcialSymbols(repeatPasswordSb);
        String securityQuestion = (String)securityQuestionInput.getSelectedItem();
        StringBuilder answerSb = new StringBuilder(answerInput.getText());
        String answer = UpdateData.dealSpcialSymbols(answerSb);
        StringBuilder verificationCodeSb = new StringBuilder(emailVerificationInput.getText());
        String verificationCode = UpdateData.dealSpcialSymbols(verificationCodeSb);
        ResultSet rs=Select.getData("select *from users where userName='"+name+"'");
        try{
            if(name.equals("") || email.equals("") || password.equals("") || securityQuestion.equals("") || answer.equals("") || verificationCode.equals("")){
                JOptionPane.showMessageDialog(null, "Every field is required.");
            }else if(code==null||!verificationCode.equals(code)){
                JOptionPane.showMessageDialog(null, "Verification email not sent or verification code is wrong.");
            }else if(rs.next() || name.equals("admin")){
                JOptionPane.showMessageDialog(null, "User name is not available.");
            }else if(Email.verifyEmailFormat(name)){
                JOptionPane.showMessageDialog(null, "User name should not be in email format.");
            }else if(!password.equals(repeatPassword)){
                JOptionPane.showMessageDialog(null, "Need to repeat the same password.");
            }else{
                String Query;
                Query = "insert into users values('"+name+"', '"+email+"', '"+password+"', '"+securityQuestion+"', '"+answer+"', 'true')";
                UpdateData.setData(Query, "Registered Successfully");
                setVisible(false);
                new Signup().setVisible(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_signupButtonActionPerformed
    
    public static String generateCode(){
        Random rand = new Random();
        StringBuilder sb = new StringBuilder();
        for(int i=0; i<10; i++){
            int randomNum = rand.nextInt(25) + 97;
            sb.append((char)randomNum);
        }
        return sb.toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField answerInput;
    private javax.swing.JLabel answerText;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailText;
    private javax.swing.JPasswordField emailVerificationInput;
    private javax.swing.JLabel emailVerificationText;
    private javax.swing.JButton emailVerifyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameText;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordText;
    private javax.swing.JPasswordField repeatPasswordInput;
    private javax.swing.JLabel repeatPasswordText;
    private javax.swing.JComboBox<String> securityQuestionInput;
    private javax.swing.JLabel securityQuestionText;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel subtitleText;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
