
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import project.*;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zhengkai Xie
 */
public class userReturn extends javax.swing.JFrame {

    /**
     * Creates new form userReturn
     */
    String myName;
    int orderId;
    int bookId;
    public userReturn(String name) {
        initComponents();
        setComponentNames();
        myName=name;
        idData.setEditable(false);
        titleData.setEditable(false);
        authorData.setEditable(false);
        genreData.setEditable(false);
        publishYearData.setEditable(false);
        editionData.setEditable(false);
        locationData.setEditable(false);
        descriptionData.setEditable(false);
        returnButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleText = new javax.swing.JLabel();
        logoutButton1 = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        idDescText = new javax.swing.JLabel();
        idData = new javax.swing.JTextField();
        titleData = new javax.swing.JTextField();
        titleDescText = new javax.swing.JLabel();
        authorDescText = new javax.swing.JLabel();
        authorData = new javax.swing.JTextField();
        genreDescText = new javax.swing.JLabel();
        genreData = new javax.swing.JTextField();
        yearDescText = new javax.swing.JLabel();
        publishYearData = new javax.swing.JTextField();
        editionDescText = new javax.swing.JLabel();
        editionData = new javax.swing.JTextField();
        locationDescText = new javax.swing.JLabel();
        locationData = new javax.swing.JTextField();
        descriptionText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionData = new javax.swing.JTextArea();
        returnButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleText.setFont(new java.awt.Font("Bernard MT Condensed", 1, 36)); // NOI18N
        titleText.setText("ZX Library System");
        titleText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleTextMouseClicked(evt);
            }
        });
        getContentPane().add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        logoutButton1.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoutButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logoutButton1.setText("Log out");
        logoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, -1, -1));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-button.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        bookTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Borrower", "Book ID", "Borrow Date", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 800, 460));

        idDescText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idDescText.setText("ID:");
        getContentPane().add(idDescText, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, -1, -1));
        getContentPane().add(idData, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, 240, -1));
        getContentPane().add(titleData, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 200, 240, -1));

        titleDescText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleDescText.setText("Title:");
        getContentPane().add(titleDescText, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 40, -1));

        authorDescText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        authorDescText.setText("Author:");
        getContentPane().add(authorDescText, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, -1, -1));
        getContentPane().add(authorData, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, 240, -1));

        genreDescText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genreDescText.setText("Genre:");
        getContentPane().add(genreDescText, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, -1, -1));
        getContentPane().add(genreData, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, 240, -1));

        yearDescText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yearDescText.setText("Publish Year:");
        getContentPane().add(yearDescText, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, -1, -1));
        getContentPane().add(publishYearData, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 310, 240, -1));

        editionDescText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editionDescText.setText("Edition:");
        getContentPane().add(editionDescText, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, -1, -1));
        getContentPane().add(editionData, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, 240, -1));

        locationDescText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        locationDescText.setText("Location:");
        getContentPane().add(locationDescText, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, -1, -1));
        getContentPane().add(locationData, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, 240, -1));

        descriptionText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        descriptionText.setText("Description:");
        getContentPane().add(descriptionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, -1, -1));

        descriptionData.setColumns(20);
        descriptionData.setLineWrap(true);
        descriptionData.setRows(5);
        jScrollPane2.setViewportView(descriptionData);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 430, 240, 110));

        returnButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 560, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleTextMouseClicked
        setVisible(false);
        new home(true, myName).setVisible(true);
    }//GEN-LAST:event_titleTextMouseClicked

    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton1ActionPerformed
        int a=JOptionPane.showConfirmDialog(null, "Do you really want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutButton1ActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        int a=JOptionPane.showConfirmDialog(null, "Do you want to exit the application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        new userHome(myName).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableMouseClicked
        int index=bookTable.getSelectedRow();
        TableModel model=bookTable.getModel();
        String stringId=model.getValueAt(index, 2).toString();
        orderId = Integer.parseInt(model.getValueAt(index, 0).toString());
        bookId=Integer.parseInt(stringId);
        ResultSet rs=Select.getData("select *from books where id='"+bookId+"'");
        try{
            if(rs.next()){
                idData.setText(stringId);
                titleData.setText(rs.getString(2));
                authorData.setText(rs.getString(3));
                genreData.setText(rs.getString(4));
                publishYearData.setText(rs.getString(5));
                editionData.setText(rs.getString(6));
                locationData.setText(rs.getString(7));
                descriptionData.setText(rs.getString(8));
                returnButton.setEnabled(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bookTableMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        StringBuilder translatedMyNameSb = new StringBuilder(myName);
        String translatedMyName = UpdateData.dealSpcialSymbols(translatedMyNameSb);
        ResultSet rs=Select.getData("select *from orders where userName='"+translatedMyName+"' and status='Incomplete'");
        DefaultTableModel model=(DefaultTableModel)bookTable.getModel();
        model.setRowCount(0);
        try{
            while(rs.next()){
                model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        UpdateData.setData("update books set status='Pending' where id='"+bookId+"'", "");
        SimpleDateFormat myFormat=new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal=Calendar.getInstance();
        String returnDate = myFormat.format(cal.getTime());
        UpdateData.setData("update orders set returnDate='"+returnDate+"', status='Return Unverified' where id='"+orderId+"'", "You have made the return request!");           
        setVisible(false);
        new userReturn(myName).setVisible(true);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void setComponentNames(){
        returnButton.setName("returnButton");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userReturn("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorData;
    private javax.swing.JLabel authorDescText;
    private javax.swing.JButton backButton;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea descriptionData;
    private javax.swing.JLabel descriptionText;
    private javax.swing.JTextField editionData;
    private javax.swing.JLabel editionDescText;
    private javax.swing.JTextField genreData;
    private javax.swing.JLabel genreDescText;
    private javax.swing.JTextField idData;
    private javax.swing.JLabel idDescText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField locationData;
    private javax.swing.JLabel locationDescText;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JTextField publishYearData;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField titleData;
    private javax.swing.JLabel titleDescText;
    private javax.swing.JLabel titleText;
    private javax.swing.JLabel yearDescText;
    // End of variables declaration//GEN-END:variables
}
