
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import project.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zhengkai Xie
 */
public class userProfile extends javax.swing.JFrame {

    /**
     * Creates new form userProfile
     */
    String myName;
    public userProfile(String name) {
        initComponents();
        myName = name;
        nameText.setText(name);
        emailData.setEditable(false);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleText = new javax.swing.JLabel();
        logoutButton1 = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        nameText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailData = new javax.swing.JTextField();
        passwordData = new javax.swing.JTextField();
        answerData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        securityQuestionData = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleText.setFont(new java.awt.Font("Bernard MT Condensed", 1, 36)); // NOI18N
        titleText.setText("ZX Library System");
        titleText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleTextMouseClicked(evt);
            }
        });
        getContentPane().add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        logoutButton1.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoutButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logoutButton1.setText("Log out");
        logoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, -1, -1));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-button.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        nameText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameText.setText("jLabel1");
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 155, 297, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 221, 52, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 262, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Security Question:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 303, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Answer:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 344, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Orders:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 377, -1, -1));

        emailData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(emailData, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 218, 370, -1));

        passwordData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(passwordData, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 259, 370, -1));

        answerData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(answerData, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 341, 370, -1));

        orderTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Book ID", "Book Title", "Borrow Date", "Deadline", "Return Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setPreferredWidth(25);
            orderTable.getColumnModel().getColumn(1).setPreferredWidth(25);
            orderTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            orderTable.getColumnModel().getColumn(3).setPreferredWidth(40);
            orderTable.getColumnModel().getColumn(4).setPreferredWidth(40);
            orderTable.getColumnModel().getColumn(5).setPreferredWidth(40);
            orderTable.getColumnModel().getColumn(6).setPreferredWidth(80);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 412, 780, 260));

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 690, -1, -1));

        securityQuestionData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        securityQuestionData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is the name of your favorite teacher in childhood?", "What is your favorite sports team?", "What is the city where you were born?", "What is your favorite food for lunch?" }));
        getContentPane().add(securityQuestionData, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 304, 365, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleTextMouseClicked
        setVisible(false);
        new home(true, myName).setVisible(true);
    }//GEN-LAST:event_titleTextMouseClicked

    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton1ActionPerformed
        int a=JOptionPane.showConfirmDialog(null, "Do you really want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutButton1ActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        int a=JOptionPane.showConfirmDialog(null, "Do you want to exit the application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        new userHome(myName).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        StringBuilder translatedMyNameSb = new StringBuilder(myName);
        String translatedMyName = UpdateData.dealSpcialSymbols(translatedMyNameSb);
        ResultSet userRs = Select.getData("select *from users where userName='"+translatedMyName+"'");
        try{
            if(userRs.next()){
                emailData.setText(userRs.getString(2));
                passwordData.setText(userRs.getString(3));
                securityQuestionData.setSelectedItem(userRs.getString(4));
                answerData.setText(userRs.getString(5));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        DefaultTableModel model = (DefaultTableModel)orderTable.getModel();
        model.setNumRows(0);
        ResultSet orderRs = Select.getData("select *from orders where userName='"+translatedMyName+"'");
        try{
            while(orderRs.next()){
                int bookId = orderRs.getInt(3);
                ResultSet bookRs = Select.getData("select *from books where id='"+bookId+"'");
                String title = new String();
                if(bookRs.next()){
                    title = bookRs.getString(2);
                }
                model.addRow(new Object[]{orderRs.getInt(1), bookId, title, orderRs.getString(4), orderRs.getString(5), orderRs.getString(6), orderRs.getString(7)});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        StringBuilder passwordSb = new StringBuilder(passwordData.getText());
        String password = UpdateData.dealSpcialSymbols(passwordSb);
        String securityQuestion = (String)securityQuestionData.getSelectedItem();
        StringBuilder answerSb = new StringBuilder(answerData.getText());
        String answer = UpdateData.dealSpcialSymbols(answerSb);
        if(password.equals("") || answer.equals("")){
            JOptionPane.showMessageDialog(null, "All fields must be filled!");
            return;
        }
        UpdateData.setData("update users set password='"+password+"', securityQuestion='"+securityQuestion+"', answer='"+answer+"' where userName='"+myName+"'", "Information saved!");
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userProfile("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerData;
    private javax.swing.JButton backButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField emailData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JLabel nameText;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextField passwordData;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> securityQuestionData;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
